import AdityaPic from '../assets/adityauser1.jpg'; // replace or duplicate for variety

const dummyProfiles = [
  {
    id: '1',
    name: 'Aditya, 25',
    images: [AdityaPic, AdityaPic, AdityaPic],
    prompts: ['Fitness is my therapy.', 'I meal prep like a pro.', 'Let’s hit PRs together.'],
    age: 25,
    goal: 'Build muscle',
    location: 'NYC',
  },
  {
    id: '2',
    name: 'Jordan, 28',
    images: ['https://placekitten.com/401/401', 'https://placekitten.com/402/402'],
    prompts: ['I’m a fan of long hikes.', 'Best gym partner ever.', 'I squat to decompress.'],
    age: 28,
    goal: 'Lose weight',
    location: 'Chicago',
  },
  {
    id: '3',
    name: 'Taylor, 24',
    images: ['https://placebear.com/400/400', 'https://placebear.com/401/401'],
    prompts: ['Never missed a Monday.', 'Love leg days.', 'Let’s lift and brunch.'],
    age: 24,
    goal: 'Tone body',
    location: 'Austin',
  },
  {
    id: '4',
    name: 'Sam, 30',
    images: ['https://randomuser.me/api/portraits/men/1.jpg'],
    prompts: ['Running clears my mind.', '5K before coffee.', 'Let’s train together.'],
    age: 30,
    goal: 'Improve endurance',
    location: 'San Diego',
  },
  {
    id: '5',
    name: 'Riley, 26',
    images: ['https://randomuser.me/api/portraits/women/2.jpg'],
    prompts: ['CrossFit is life.', 'Sore today, strong tomorrow.', 'Looking for a spotter.'],
    age: 26,
    goal: 'CrossFit goals',
    location: 'Miami',
  },
  {
    id: '6',
    name: 'Chris, 27',
    images: ['https://placekitten.com/403/403'],
    prompts: ['Lifting is meditation.', 'Beast mode 24/7.', 'Let’s talk macros.'],
    age: 27,
    goal: 'Bulk up',
    location: 'Seattle',
  },
  {
    id: '7',
    name: 'Drew, 29',
    images: ['https://placebear.com/402/402'],
    prompts: ['Stretching > stress.', 'Mobility king.', 'Yoga date?'],
    age: 29,
    goal: 'Improve flexibility',
    location: 'Denver',
  },
  {
    id: '8',
    name: 'Alex, 23',
    images: ['https://placekitten.com/405/405'],
    prompts: ['Track athlete.', 'Love cardio.', '100m in under 12s.'],
    age: 23,
    goal: 'Speed training',
    location: 'Boston',
  },
  {
    id: '9',
    name: 'Sky, 31',
    images: ['https://randomuser.me/api/portraits/women/5.jpg'],
    prompts: ['Adventure is the best workout.', 'Climb every mountain.', 'Hiking is healing.'],
    age: 31,
    goal: 'Outdoor fitness',
    location: 'Phoenix',
  },
  {
    id: '10',
    name: 'Morgan, 27',
    images: ['https://randomuser.me/api/portraits/men/6.jpg'],
    prompts: ['Cycle everywhere.', 'Spin class addict.', 'Catch me on a bike trail.'],
    age: 27,
    goal: 'Cycling',
    location: 'Portland',
  },
  // Add 10 more with similar structure...
];

export default dummyProfiles;
